name: 'Terraform'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: testsecret

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: echo secret
      run: echo "Secret value is ${{ secrets.MYSECRET }}"

    - name: echo evironment variable
      run: echo "Enviroment value is ${{ vars.MYENVVARIABLE }}"

    - name: running scripts
      run: ./myscript.sh

    - name: running second script
      working-directory: directory
      run: ./mytestscript.sh

