name: 'Terraform'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: testsecret
    outputs:
      output1: ${{steps.step1.outputs.test}}
      output2: ${{steps.step2.outputs.test}}
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: echo secret
      run: echo "Secret value is ${{ secrets.MYSECRET }}"

    - name: echo evironment variable
      id: step1
      run: |
        echo "Enviroment value is ${{ vars.MYENVVARIABLE }}" 
        GITHUB_OUTPUT=$(echo "Passing value")

    - name: running scripts
      run: |
        ./myscript.sh
      id: step2

    - name: running second script
      working-directory: directory
      run: ./mytestscript.sh

  job2:

    runs-on: ubuntu-latest
    needs: terraform
    defaults:
      run:
        shell: bash
    steps:
      - env:
          OUTPUT1: ${{needs.terraform.outputs.output1}}
          OUTPUT2: ${{needs.terraform.outputs.output2}}
        run: echo "$OUTPUT1 $OUTPUT2"
    

